### ISSUE TITLE
File Split  --limitmb

### ISSUE THREAD

**Issue by yoanhg421** [tsopeh/mapaki#2]
Hi. I wanted to thank you for making this little program. 
I just tried it and it works amazing. 

I have a question tough. For long running mangas like the One Piece that is about 7.7GB  and counting. I'm worried about being too large to transfer and too slow to open in a kindle device.

Any thoughts on that?

I currently use celogeek/go-comic-converter to make epubs 
and I want to start using mapaki for awz3 but some mangas are so big that it's basically all that fits in the kindle. 

Any tricks or suggestions?

**Comment by yoanhg421** [comment]
I think it's too large to handle, it died after 15 minutes. 
```
Processing images 20557 / 20557 [------------------------------] 100.00% 279 p/s
Exporting manga ↗                                                                                                                        
zsh: killed     mapaki -i One\ Piece

```

**Comment by tsopeh** [comment]
Hi there @yoanhg421 👋 

> I have a question tough. For long running mangas like the One Piece that is about 7.7GB and counting. I'm worried about being too large to transfer and too slow to open in a kindle device.
Any thoughts on that?

I've only converted mangas up to 2.5GB. Kindle handles them just fine, but I've noticed that the performance is better if you leave some empty space on the device. I don't know if it can handle an 8GB manga as well.

> I think it's too large to handle, it died after 15 minutes.

Most likely you went out of RAM. I've noticed that the RAM consumption of the [mobi](https://github.com/leotaku/mobi) library can get really high, really quickly. For packaging of a ~2GB manga, it might require more than 10GB of RAM.

A quick solution might be to manually split chapters into separate directories (e.g. up to 2GB) and package them separately.

**Comment by yoanhg421** [comment]
I See. Splitting directories might be the easiest way to go about it. 

The better route might be to create multiple books after a certain MB limit is reached. 
like `Manga [1-3].azw3` or `Manga part 1 of 3.azw3`

I'll mess around with it. 
It seems like a good opportunity to learn Go.

Thank you
